package repositories

import (
	"context"
	"pixkeys/entities"
	"pixkeys/infra"
)

type KeyTypeFinder interface {
	FindByID(int) (entities.KeyType, error)
}

func (k keyType) FindByID(id int) (entities.KeyType, error) {
	row := infra.DB.QueryRowContext(context.Background(),
		"SELECT ID, Name, Format, AutomaticallyGenerated FROM api_pix_keys.KeyTypes WHERE ID = ?", id)

	var ID int64
	var name string
	var format string
	var autoGenerated bool

	err := row.Scan(&ID, &name, &format, &autoGenerated)

	if err != nil {
		return entities.KeyType{}, err
	}

	return entities.KeyType{
		ID:             ID,
		Name:           name,
		Format:         format,
		AutomaticallyGenerated: autoGenerated,
	}, nil
}

var (
	KeyTypeRepo = keyType{}
)
